/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Luciano HP
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        MenuVenta = new javax.swing.JMenu();
        ServicioComun = new javax.swing.JMenuItem();
        MenuReserva = new javax.swing.JMenu();
        Reserva = new javax.swing.JMenuItem();
        MenuBarco = new javax.swing.JMenu();
        MenuAgregarBarco = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(102, 102, 102));

        MenuVenta.setText("Venta");

        ServicioComun.setText("Boleto Comun");
        ServicioComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicioComunActionPerformed(evt);
            }
        });
        MenuVenta.add(ServicioComun);

        barraMenu.add(MenuVenta);

        MenuReserva.setText("Reserva");

        Reserva.setText("Reserva Servicio Especial");
        Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaActionPerformed(evt);
            }
        });
        MenuReserva.add(Reserva);

        barraMenu.add(MenuReserva);

        MenuBarco.setText("Embarcación");

        MenuAgregarBarco.setText("Agregar Embarcación");
        MenuAgregarBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgregarBarcoActionPerformed(evt);
            }
        });
        MenuBarco.add(MenuAgregarBarco);

        barraMenu.add(MenuBarco);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaActionPerformed
      InterReserva unaReserva = new InterReserva();
      Escritorio.add(unaReserva);
      unaReserva.show();
      unaReserva.setVisible(true);
      
    }//GEN-LAST:event_ReservaActionPerformed

    private void ServicioComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicioComunActionPerformed
        InterServicioComun unServ=new InterServicioComun();
        Escritorio.add(unServ);
        unServ.show();
        unServ.setVisible(true);
    }//GEN-LAST:event_ServicioComunActionPerformed

    private void MenuAgregarBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgregarBarcoActionPerformed
        InterEmbarcacion unBarco = new InterEmbarcacion();
        Escritorio.add(unBarco);
        unBarco.show();
        unBarco.setVisible(true);
        
    }//GEN-LAST:event_MenuAgregarBarcoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MenuAgregarBarco;
    private javax.swing.JMenu MenuBarco;
    private javax.swing.JMenu MenuReserva;
    private javax.swing.JMenu MenuVenta;
    private javax.swing.JMenuItem Reserva;
    private javax.swing.JMenuItem ServicioComun;
    private javax.swing.JMenuBar barraMenu;
    // End of variables declaration//GEN-END:variables
}
